name: Initial build for x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 4.4.1
      
      - name: build
        run: |
          .\bootstrap.bat
          .\build_w32.bat gcc
          
      - name: rename
        run: move GccRel\gnumake.exe make.exe
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "make.exe"
          tag: 4.4.1
