name: Build for x86_64

on:
  workflow_dispatch:
  create:
    ref_type: "tag"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: build
        run: |
          .\bootstrap.bat
          .\build_w32.bat gcc
          
      - name: install
        run: move GccRel\gnumake.exe make.exe
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "make.exe"
